// <auto-generated />
using System;
using LearnerCenter.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnerCenter.API.Migrations
{
    [DbContext(typeof(LearnerCenterDbContext))]
    partial class LearnerCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnerCenter.API.Models.Campus", b =>
                {
                    b.Property<Guid>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CampusCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CampusId");

                    b.HasIndex("CampusCode")
                        .IsUnique()
                        .HasFilter("[CampusCode] IS NOT NULL");

                    b.ToTable("Campuses");

                    b.HasData(
                        new
                        {
                            CampusId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Address = "123 University Ave",
                            CampusCode = "SU-MAIN",
                            CampusName = "State University Main Campus",
                            City = "Springfield",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@stateuniv.edu",
                            IsActive = true,
                            PhoneNumber = "(555) 123-4567",
                            State = "IL",
                            ZipCode = "62701"
                        },
                        new
                        {
                            CampusId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            Address = "456 College St",
                            CampusCode = "CC-DOWN",
                            CampusName = "Community College Downtown",
                            City = "Springfield",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admissions@ccdowntown.edu",
                            IsActive = true,
                            PhoneNumber = "(555) 234-5678",
                            State = "IL",
                            ZipCode = "62702"
                        },
                        new
                        {
                            CampusId = new Guid("c3d4e5f6-a7b8-9012-cdef-345678901234"),
                            Address = "789 Tech Blvd",
                            CampusCode = "TI-NORTH",
                            CampusName = "Technical Institute North",
                            City = "Rockford",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@technorth.edu",
                            IsActive = true,
                            PhoneNumber = "(555) 345-6789",
                            State = "IL",
                            ZipCode = "61101"
                        },
                        new
                        {
                            CampusId = new Guid("d4e5f6a7-b8c9-0123-def0-456789012345"),
                            Address = "321 Arts Way",
                            CampusCode = "LAC-MAIN",
                            CampusName = "Liberal Arts College",
                            City = "Peoria",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@liberalarts.edu",
                            IsActive = true,
                            PhoneNumber = "(555) 456-7890",
                            State = "IL",
                            ZipCode = "61602"
                        },
                        new
                        {
                            CampusId = new Guid("e5f6a7b8-c9d0-1234-ef01-567890123456"),
                            Address = "654 Commerce Dr",
                            CampusCode = "BSC-CENT",
                            CampusName = "Business School Central",
                            City = "Chicago",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admissions@businesscentral.edu",
                            IsActive = true,
                            PhoneNumber = "(555) 567-8901",
                            State = "IL",
                            ZipCode = "60601"
                        },
                        new
                        {
                            CampusId = new Guid("f6a7b8c9-d0e1-2345-f012-678901234567"),
                            Address = "1200 Ocean Drive",
                            CampusCode = "SCC-MAIN",
                            CampusName = "Sunshine Community College",
                            City = "Miami",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@sunshinecc.edu",
                            IsActive = true,
                            PhoneNumber = "(305) 123-4567",
                            State = "FL",
                            ZipCode = "33139"
                        },
                        new
                        {
                            CampusId = new Guid("a7b8c9d0-e1f2-3456-0123-789012345678"),
                            Address = "850 Alpine Way",
                            CampusCode = "MVTI-CO",
                            CampusName = "Mountain View Technical Institute",
                            City = "Denver",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admissions@mvti.edu",
                            IsActive = true,
                            PhoneNumber = "(303) 234-5678",
                            State = "CO",
                            ZipCode = "80202"
                        },
                        new
                        {
                            CampusId = new Guid("b8c9d0e1-f2a3-4567-1234-890123456789"),
                            Address = "2500 Rodeo Boulevard",
                            CampusCode = "LSU-TX",
                            CampusName = "Lone Star University",
                            City = "Houston",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@lonestaruniv.edu",
                            IsActive = true,
                            PhoneNumber = "(713) 345-6789",
                            State = "TX",
                            ZipCode = "77002"
                        },
                        new
                        {
                            CampusId = new Guid("c9d0e1f2-a3b4-5678-2345-901234567890"),
                            Address = "777 Market Street",
                            CampusCode = "GGC-SF",
                            CampusName = "Golden Gate College",
                            City = "San Francisco",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@goldengatecc.edu",
                            IsActive = true,
                            PhoneNumber = "(415) 456-7890",
                            State = "CA",
                            ZipCode = "94103"
                        },
                        new
                        {
                            CampusId = new Guid("d0e1f2a3-b4c5-6789-3456-012345678901"),
                            Address = "350 Fifth Avenue",
                            CampusCode = "ESI-NYC",
                            CampusName = "Empire State Institute",
                            City = "New York",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@empireinst.edu",
                            IsActive = true,
                            PhoneNumber = "(212) 567-8901",
                            State = "NY",
                            ZipCode = "10118"
                        },
                        new
                        {
                            CampusId = new Guid("e1f2a3b4-c5d6-7890-4567-123456789012"),
                            Address = "1500 Cactus Road",
                            CampusCode = "DIU-AZ",
                            CampusName = "Desert Innovation University",
                            City = "Phoenix",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admissions@desertinnovation.edu",
                            IsActive = true,
                            PhoneNumber = "(602) 678-9012",
                            State = "AZ",
                            ZipCode = "85001"
                        },
                        new
                        {
                            CampusId = new Guid("f2a3b4c5-d6e7-8901-5678-234567890123"),
                            Address = "900 Harbor Drive",
                            CampusCode = "GLTC-MI",
                            CampusName = "Great Lakes Technical College",
                            City = "Detroit",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@greatlakestech.edu",
                            IsActive = true,
                            PhoneNumber = "(313) 789-0123",
                            State = "MI",
                            ZipCode = "48201"
                        },
                        new
                        {
                            CampusId = new Guid("a3b4c5d6-e7f8-9012-6789-345678901234"),
                            Address = "1400 Pine Street",
                            CampusCode = "ECU-WA",
                            CampusName = "Emerald City University",
                            City = "Seattle",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@emeraldcity.edu",
                            IsActive = true,
                            PhoneNumber = "(206) 890-1234",
                            State = "WA",
                            ZipCode = "98101"
                        },
                        new
                        {
                            CampusId = new Guid("b4c5d6e7-f8a9-0123-7890-456789012345"),
                            Address = "625 Mountain View Lane",
                            CampusCode = "BRCC-VA",
                            CampusName = "Blue Ridge Community College",
                            City = "Richmond",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@blueridgecc.edu",
                            IsActive = true,
                            PhoneNumber = "(804) 901-2345",
                            State = "VA",
                            ZipCode = "23219"
                        },
                        new
                        {
                            CampusId = new Guid("c5d6e7f8-a9b0-1234-8901-567890123456"),
                            Address = "1100 Peachtree Street",
                            CampusCode = "PSI-GA",
                            CampusName = "Peach State Institute",
                            City = "Atlanta",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admissions@peachstate.edu",
                            IsActive = true,
                            PhoneNumber = "(404) 012-3456",
                            State = "GA",
                            ZipCode = "30309"
                        });
                });

            modelBuilder.Entity("LearnerCenter.API.Models.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CourseId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("CourseCode", "EnrollmentId")
                        .IsUnique();

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("aa111111-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            CourseCode = "CS101",
                            CourseName = "Introduction to Programming",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Basic programming concepts and problem solving",
                            EnrollmentId = new Guid("f6a7b8c9-d0e1-2345-f012-678901234567"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("bb222222-cccc-dddd-eeee-ffffffffffff"),
                            CourseCode = "CS102",
                            CourseName = "Data Structures",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Fundamental data structures and algorithms",
                            EnrollmentId = new Guid("f6a7b8c9-d0e1-2345-f012-678901234567"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("cc333333-dddd-eeee-ffff-000000000000"),
                            CourseCode = "MATH150",
                            CourseName = "Calculus I",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Differential calculus and applications",
                            EnrollmentId = new Guid("f6a7b8c9-d0e1-2345-f012-678901234567"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("dd444444-eeee-ffff-0000-111111111111"),
                            CourseCode = "ENGR101",
                            CourseName = "Engineering Fundamentals",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Introduction to engineering principles",
                            EnrollmentId = new Guid("a7b8c9d0-e1f2-3456-0123-789012345678"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("ee555555-ffff-0000-1111-222222222222"),
                            CourseCode = "PHYS210",
                            CourseName = "Physics for Engineers I",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Mechanics and thermodynamics",
                            EnrollmentId = new Guid("a7b8c9d0-e1f2-3456-0123-789012345678"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("ff666666-0000-1111-2222-333333333333"),
                            CourseCode = "BIO120",
                            CourseName = "General Biology I",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Cell biology and genetics",
                            EnrollmentId = new Guid("b8c9d0e1-f2a3-4567-1234-890123456789"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("00777777-1111-2222-3333-444444444444"),
                            CourseCode = "CHEM130",
                            CourseName = "General Chemistry I",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Basic chemical principles",
                            EnrollmentId = new Guid("b8c9d0e1-f2a3-4567-1234-890123456789"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("11888888-2222-3333-4444-555555555555"),
                            CourseCode = "BUS101",
                            CourseName = "Introduction to Business",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Business fundamentals",
                            EnrollmentId = new Guid("c9d0e1f2-a3b4-5678-2345-901234567890"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("22999999-3333-4444-5555-666666666666"),
                            CourseCode = "ACC110",
                            CourseName = "Basic Accounting",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Accounting principles",
                            EnrollmentId = new Guid("c9d0e1f2-a3b4-5678-2345-901234567890"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("33aaaaaa-4444-5555-6666-777777777777"),
                            CourseCode = "NUR100",
                            CourseName = "Introduction to Nursing",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Basic nursing concepts",
                            EnrollmentId = new Guid("d0e1f2a3-b4c5-6789-3456-012345678901"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("44bbbbbb-5555-6666-7777-888888888888"),
                            CourseCode = "BIO201",
                            CourseName = "Anatomy & Physiology I",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Human body systems",
                            EnrollmentId = new Guid("d0e1f2a3-b4c5-6789-3456-012345678901"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("55cccccc-6666-7777-8888-999999999999"),
                            CourseCode = "AUTO120",
                            CourseName = "Automotive Basics",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 5,
                            Description = "Introduction to automotive systems",
                            EnrollmentId = new Guid("f2a3b4c5-d6e7-8901-5678-234567890123"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("66dddddd-7777-8888-9999-aaaaaaaaaaaa"),
                            CourseCode = "AUTO220",
                            CourseName = "Engine Repair",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 5,
                            Description = "Engine diagnosis and repair",
                            EnrollmentId = new Guid("f2a3b4c5-d6e7-8901-5678-234567890123"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("77eeeeee-8888-9999-aaaa-bbbbbbbbbbbb"),
                            CourseCode = "ART110",
                            CourseName = "Drawing Fundamentals",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Basic drawing techniques",
                            EnrollmentId = new Guid("c5d6e7f8-a9b0-1234-8901-567890123456"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("88ffffff-9999-aaaa-bbbb-cccccccccccc"),
                            CourseCode = "ART210",
                            CourseName = "Painting I",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Introduction to painting",
                            EnrollmentId = new Guid("c5d6e7f8-a9b0-1234-8901-567890123456"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("99000000-aaaa-bbbb-cccc-dddddddddddd"),
                            CourseCode = "MBA600",
                            CourseName = "Strategic Management",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Advanced business strategy",
                            EnrollmentId = new Guid("e7f8a9b0-c1d2-3456-0123-789012345678"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("aa111111-bbbb-cccc-dddd-eeeeeeeeeeef"),
                            CourseCode = "MBA610",
                            CourseName = "Financial Management",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Corporate finance principles",
                            EnrollmentId = new Guid("e7f8a9b0-c1d2-3456-0123-789012345678"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890"),
                            CourseCode = "MA101",
                            CourseName = "Medical Terminology",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Medical language and terminology",
                            EnrollmentId = new Guid("54321098-dcba-0987-6543-210987654321"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("2b3c4d5e-6f70-8901-bcde-f12345678901"),
                            CourseCode = "MA201",
                            CourseName = "Clinical Procedures",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Basic clinical procedures for medical assistants",
                            EnrollmentId = new Guid("54321098-dcba-0987-6543-210987654321"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("3c4d5e6f-7080-9012-cdef-123456789012"),
                            CourseCode = "CYB101",
                            CourseName = "Introduction to Cybersecurity",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Fundamentals of cybersecurity",
                            EnrollmentId = new Guid("87654321-0fed-cba0-9876-543210987654"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("4d5e6f70-8090-1234-def0-234567890123"),
                            CourseCode = "CYB301",
                            CourseName = "Network Security",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Network security protocols and defense",
                            EnrollmentId = new Guid("87654321-0fed-cba0-9876-543210987654"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("5e6f7080-90a0-2345-ef01-345678901234"),
                            CourseCode = "CUL110",
                            CourseName = "Culinary Fundamentals",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Basic cooking techniques and food safety",
                            EnrollmentId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567891"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("6f708090-a0b0-3456-f012-456789012345"),
                            CourseCode = "CUL220",
                            CourseName = "Advanced Culinary Techniques",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 5,
                            Description = "Professional cooking methods",
                            EnrollmentId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567891"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("708090a0-b0c0-4567-0123-567890123456"),
                            CourseCode = "MKTG150",
                            CourseName = "Digital Marketing Fundamentals",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Introduction to digital marketing strategies",
                            EnrollmentId = new Guid("2b3c4d5e-6f70-8901-bcde-f12345678902"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("8090a0b0-c0d0-5678-1234-678901234567"),
                            CourseCode = "MKTG350",
                            CourseName = "Social Media Marketing",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Social media strategy and analytics",
                            EnrollmentId = new Guid("2b3c4d5e-6f70-8901-bcde-f12345678902"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("90a0b0c0-d0e0-6789-2345-789012345678"),
                            CourseCode = "PTA101",
                            CourseName = "Introduction to Physical Therapy",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Foundations of physical therapy practice",
                            EnrollmentId = new Guid("3c4d5e6f-7080-9012-cdef-123456789013"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("a0b0c0d0-e0f0-789a-3456-890123456789"),
                            CourseCode = "PTA201",
                            CourseName = "Therapeutic Exercise",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Exercise principles and techniques",
                            EnrollmentId = new Guid("3c4d5e6f-7080-9012-cdef-123456789013"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("b0c0d0e0-f0a1-89ab-4567-901234567890"),
                            CourseCode = "WEB101",
                            CourseName = "HTML & CSS Fundamentals",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Web development basics",
                            EnrollmentId = new Guid("4d5e6f70-8090-1234-def0-234567890124"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("c0d0e0f0-a1b2-9abc-5678-012345678901"),
                            CourseCode = "WEB301",
                            CourseName = "JavaScript Programming",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Client-side and server-side JavaScript",
                            EnrollmentId = new Guid("4d5e6f70-8090-1234-def0-234567890124"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("d0e0f0a1-b2c3-abcd-6789-123456789012"),
                            CourseCode = "DH101",
                            CourseName = "Oral Anatomy",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Structure and function of oral cavity",
                            EnrollmentId = new Guid("5e6f7080-90a0-2345-ef01-345678901235"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("e0f0a1b2-c3d4-bcde-789a-234567890123"),
                            CourseCode = "DH201",
                            CourseName = "Periodontal Therapy",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Treatment of gum disease",
                            EnrollmentId = new Guid("5e6f7080-90a0-2345-ef01-345678901235"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("f0a1b2c3-d4e5-cdef-89ab-345678901234"),
                            CourseCode = "VET101",
                            CourseName = "Animal Anatomy & Physiology",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Animal body systems and functions",
                            EnrollmentId = new Guid("6f708090-a0b0-3456-f012-456789012346"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("a1b2c3d4-e5f6-def0-9abc-456789012345"),
                            CourseCode = "VET201",
                            CourseName = "Veterinary Pharmacology",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Animal medications and dosages",
                            EnrollmentId = new Guid("6f708090-a0b0-3456-f012-456789012346"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("b2c3d4e5-f6a7-ef01-abcd-567890123456"),
                            CourseCode = "WELD101",
                            CourseName = "Introduction to Welding",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Basic welding processes and safety",
                            EnrollmentId = new Guid("708090a0-b0c0-4567-0123-567890123457"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("c3d4e5f6-a7b8-f012-bcde-678901234567"),
                            CourseCode = "WELD301",
                            CourseName = "Advanced Welding Techniques",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 5,
                            Description = "Specialized welding methods",
                            EnrollmentId = new Guid("708090a0-b0c0-4567-0123-567890123457"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("d4e5f6a7-b8c9-0123-cdef-789012345678"),
                            CourseCode = "GD101",
                            CourseName = "Design Fundamentals",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Basic principles of graphic design",
                            EnrollmentId = new Guid("8090a0b0-c0d0-5678-1234-678901234568"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("e5f6a7b8-c9d0-1234-def0-890123456789"),
                            CourseCode = "GD301",
                            CourseName = "Digital Design Software",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Adobe Creative Suite mastery",
                            EnrollmentId = new Guid("8090a0b0-c0d0-5678-1234-678901234568"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("f6a7b8c9-d0e1-2345-ef01-901234567890"),
                            CourseCode = "CJ101",
                            CourseName = "Introduction to Criminal Justice",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Overview of the criminal justice system",
                            EnrollmentId = new Guid("90a0b0c0-d0e0-6789-2345-789012345679"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("a7b8c9d0-e1f2-3456-f012-012345678901"),
                            CourseCode = "CJ301",
                            CourseName = "Criminal Investigation",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Investigation techniques and procedures",
                            EnrollmentId = new Guid("90a0b0c0-d0e0-6789-2345-789012345679"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("b8c9d0e1-f2a3-4567-0123-123456789012"),
                            CourseCode = "ECE101",
                            CourseName = "Child Development",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Physical, cognitive, and social development",
                            EnrollmentId = new Guid("a0b0c0d0-e0f0-789a-3456-890123456780"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("c9d0e1f2-a3b4-5678-1234-234567890123"),
                            CourseCode = "ECE201",
                            CourseName = "Curriculum Planning",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Age-appropriate curriculum development",
                            EnrollmentId = new Guid("a0b0c0d0-e0f0-789a-3456-890123456780"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("d0e1f2a3-b4c5-6789-2345-345678901234"),
                            CourseCode = "HVAC101",
                            CourseName = "HVAC Fundamentals",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Heating, ventilation, and air conditioning basics",
                            EnrollmentId = new Guid("b0c0d0e0-f0a1-89ab-4567-901234567891"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("e1f2a3b4-c5d6-789a-3456-456789012345"),
                            CourseCode = "HVAC301",
                            CourseName = "Refrigeration Systems",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 5,
                            Description = "Commercial and residential refrigeration",
                            EnrollmentId = new Guid("b0c0d0e0-f0a1-89ab-4567-901234567891"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("f2a3b4c5-d6e7-89ab-4567-567890123456"),
                            CourseCode = "FASH101",
                            CourseName = "Fashion Illustration",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 3,
                            Description = "Fashion drawing and design techniques",
                            EnrollmentId = new Guid("09876543-210f-edcb-a098-765432109876"),
                            IsActive = true
                        },
                        new
                        {
                            CourseId = new Guid("a3b4c5d6-e7f8-9abc-5678-678901234567"),
                            CourseCode = "FASH301",
                            CourseName = "Pattern Making",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditHours = 4,
                            Description = "Creating patterns for garment construction",
                            EnrollmentId = new Guid("09876543-210f-edcb-a098-765432109876"),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("LearnerCenter.API.Models.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Degree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CampusId");

                    b.HasIndex("ProgramName", "CampusId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = new Guid("f6a7b8c9-d0e1-2345-f012-678901234567"),
                            CampusId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Comprehensive computer science program covering programming, algorithms, and software engineering",
                            IsActive = true,
                            ProgramName = "Computer Science Degree"
                        },
                        new
                        {
                            EnrollmentId = new Guid("a7b8c9d0-e1f2-3456-0123-789012345678"),
                            CampusId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Engineering",
                            Description = "Engineering fundamentals with specializations available",
                            IsActive = true,
                            ProgramName = "Engineering Program"
                        },
                        new
                        {
                            EnrollmentId = new Guid("b8c9d0e1-f2a3-4567-1234-890123456789"),
                            CampusId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Pre-medical preparation with required science courses",
                            IsActive = true,
                            ProgramName = "Pre-Medicine Track"
                        },
                        new
                        {
                            EnrollmentId = new Guid("c9d0e1f2-a3b4-5678-2345-901234567890"),
                            CampusId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Practical business skills and management fundamentals",
                            IsActive = true,
                            ProgramName = "Business Administration"
                        },
                        new
                        {
                            EnrollmentId = new Guid("d0e1f2a3-b4c5-6789-3456-012345678901"),
                            CampusId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Science in Nursing",
                            Description = "Registered nurse preparation program",
                            IsActive = true,
                            ProgramName = "Nursing Program"
                        },
                        new
                        {
                            EnrollmentId = new Guid("e1f2a3b4-c5d6-7890-4567-123456789012"),
                            CampusId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Arts",
                            Description = "Liberal arts foundation for university transfer",
                            IsActive = true,
                            ProgramName = "General Education Transfer"
                        },
                        new
                        {
                            EnrollmentId = new Guid("f2a3b4c5-d6e7-8901-5678-234567890123"),
                            CampusId = new Guid("c3d4e5f6-a7b8-9012-cdef-345678901234"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Certificate",
                            Description = "Automotive repair and maintenance certification",
                            IsActive = true,
                            ProgramName = "Automotive Technology"
                        },
                        new
                        {
                            EnrollmentId = new Guid("a3b4c5d6-e7f8-9012-6789-345678901234"),
                            CampusId = new Guid("c3d4e5f6-a7b8-9012-cdef-345678901234"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Industrial and residential electrical systems",
                            IsActive = true,
                            ProgramName = "Electrical Technology"
                        },
                        new
                        {
                            EnrollmentId = new Guid("b4c5d6e7-f8a9-0123-7890-456789012345"),
                            CampusId = new Guid("c3d4e5f6-a7b8-9012-cdef-345678901234"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Certificate",
                            Description = "Professional welding techniques and safety",
                            IsActive = true,
                            ProgramName = "Welding Certification"
                        },
                        new
                        {
                            EnrollmentId = new Guid("c5d6e7f8-a9b0-1234-8901-567890123456"),
                            CampusId = new Guid("d4e5f6a7-b8c9-0123-def0-456789012345"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Fine Arts",
                            Description = "Creative arts with studio and theory components",
                            IsActive = true,
                            ProgramName = "Fine Arts Degree"
                        },
                        new
                        {
                            EnrollmentId = new Guid("d6e7f8a9-b0c1-2345-9012-678901234567"),
                            CampusId = new Guid("d4e5f6a7-b8c9-0123-def0-456789012345"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Arts",
                            Description = "English literature and creative writing program",
                            IsActive = true,
                            ProgramName = "Literature and Writing"
                        },
                        new
                        {
                            EnrollmentId = new Guid("e7f8a9b0-c1d2-3456-0123-789012345678"),
                            CampusId = new Guid("e5f6a7b8-c9d0-1234-ef01-567890123456"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Master of Business Administration",
                            Description = "Advanced business management and leadership",
                            IsActive = true,
                            ProgramName = "MBA Program"
                        },
                        new
                        {
                            EnrollmentId = new Guid("f8a9b0c1-d2e3-4567-1234-890123456789"),
                            CampusId = new Guid("e5f6a7b8-c9d0-1234-ef01-567890123456"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Financial accounting and business finance",
                            IsActive = true,
                            ProgramName = "Accounting Degree"
                        },
                        new
                        {
                            EnrollmentId = new Guid("a9b8c7d6-e5f4-3210-9876-543210fedcba"),
                            CampusId = new Guid("f6a7b8c9-d0e1-2345-f012-678901234567"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Science",
                            Description = "Study of ocean ecosystems and marine life",
                            IsActive = true,
                            ProgramName = "Marine Biology"
                        },
                        new
                        {
                            EnrollmentId = new Guid("b8c7d6e5-f4a3-2109-8765-4321fedcba09"),
                            CampusId = new Guid("f6a7b8c9-d0e1-2345-f012-678901234567"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Tourism and hotel management program",
                            IsActive = true,
                            ProgramName = "Hospitality Management"
                        },
                        new
                        {
                            EnrollmentId = new Guid("c7d6e5f4-a3b2-1098-7654-321fedcba098"),
                            CampusId = new Guid("a7b8c9d0-e1f2-3456-0123-789012345678"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Solar and wind energy systems technology",
                            IsActive = true,
                            ProgramName = "Renewable Energy Technology"
                        },
                        new
                        {
                            EnrollmentId = new Guid("d6e5f4a3-b210-9876-5432-1fedcba09876"),
                            CampusId = new Guid("a7b8c9d0-e1f2-3456-0123-789012345678"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Certificate",
                            Description = "Emergency response in mountainous terrain",
                            IsActive = true,
                            ProgramName = "Mountain Rescue Operations"
                        },
                        new
                        {
                            EnrollmentId = new Guid("e5f4a3b2-1098-7654-3210-fedcba098765"),
                            CampusId = new Guid("b8c9d0e1-f2a3-4567-1234-890123456789"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Oil and gas extraction technology",
                            IsActive = true,
                            ProgramName = "Petroleum Engineering"
                        },
                        new
                        {
                            EnrollmentId = new Guid("f4a3b210-9876-5432-10fe-dcba09876543"),
                            CampusId = new Guid("b8c9d0e1-f2a3-4567-1234-890123456789"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Livestock and agricultural operations",
                            IsActive = true,
                            ProgramName = "Ranch Management"
                        },
                        new
                        {
                            EnrollmentId = new Guid("a3b21098-7654-3210-fedc-ba0987654321"),
                            CampusId = new Guid("c9d0e1f2-a3b4-5678-2345-901234567890"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Modern software engineering and development",
                            IsActive = true,
                            ProgramName = "Software Development"
                        },
                        new
                        {
                            EnrollmentId = new Guid("b2109876-5432-10fe-dcba-098765432109"),
                            CampusId = new Guid("c9d0e1f2-a3b4-5678-2345-901234567890"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Fine Arts",
                            Description = "Digital design and multimedia production",
                            IsActive = true,
                            ProgramName = "Digital Media Arts"
                        },
                        new
                        {
                            EnrollmentId = new Guid("10987654-3210-fedc-ba09-876543210987"),
                            CampusId = new Guid("d0e1f2a3-b4c5-6789-3456-012345678901"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Financial markets and investment banking",
                            IsActive = true,
                            ProgramName = "Finance and Banking"
                        },
                        new
                        {
                            EnrollmentId = new Guid("09876543-210f-edcb-a098-765432109876"),
                            CampusId = new Guid("d0e1f2a3-b4c5-6789-3456-012345678901"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Arts",
                            Description = "Contemporary fashion design and merchandising",
                            IsActive = true,
                            ProgramName = "Fashion Design"
                        },
                        new
                        {
                            EnrollmentId = new Guid("87654321-0fed-cba0-9876-543210987654"),
                            CampusId = new Guid("e1f2a3b4-c5d6-7890-4567-123456789012"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Information security and ethical hacking",
                            IsActive = true,
                            ProgramName = "Cybersecurity"
                        },
                        new
                        {
                            EnrollmentId = new Guid("76543210-fedc-ba09-8765-432109876543"),
                            CampusId = new Guid("f2a3b4c5-d6e7-8901-5678-234567890123"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Vehicle design and manufacturing technology",
                            IsActive = true,
                            ProgramName = "Automotive Engineering"
                        },
                        new
                        {
                            EnrollmentId = new Guid("65432109-edcb-a098-7654-321098765432"),
                            CampusId = new Guid("a3b4c5d6-e7f8-9012-6789-345678901234"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Ecology and environmental conservation",
                            IsActive = true,
                            ProgramName = "Environmental Science"
                        },
                        new
                        {
                            EnrollmentId = new Guid("54321098-dcba-0987-6543-210987654321"),
                            CampusId = new Guid("b4c5d6e7-f8a9-0123-7890-456789012345"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Science",
                            Description = "Pre-health and medical assistant preparation",
                            IsActive = true,
                            ProgramName = "Health Sciences"
                        },
                        new
                        {
                            EnrollmentId = new Guid("43210987-cba0-9876-5432-109876543210"),
                            CampusId = new Guid("c5d6e7f8-a9b0-1234-8901-567890123456"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Modern farming and crop management",
                            IsActive = true,
                            ProgramName = "Agricultural Technology"
                        },
                        new
                        {
                            EnrollmentId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567891"),
                            CampusId = new Guid("f6a7b8c9-d0e1-2345-f012-678901234567"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Professional culinary techniques and food service management",
                            IsActive = true,
                            ProgramName = "Culinary Arts"
                        },
                        new
                        {
                            EnrollmentId = new Guid("2b3c4d5e-6f70-8901-bcde-f12345678902"),
                            CampusId = new Guid("c9d0e1f2-a3b4-5678-2345-901234567890"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Business Administration",
                            Description = "Online marketing strategies and social media management",
                            IsActive = true,
                            ProgramName = "Digital Marketing"
                        },
                        new
                        {
                            EnrollmentId = new Guid("3c4d5e6f-7080-9012-cdef-123456789013"),
                            CampusId = new Guid("b4c5d6e7-f8a9-0123-7890-456789012345"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Physical therapy support and rehabilitation techniques",
                            IsActive = true,
                            ProgramName = "Physical Therapy Assistant"
                        },
                        new
                        {
                            EnrollmentId = new Guid("4d5e6f70-8090-1234-def0-234567890124"),
                            CampusId = new Guid("c9d0e1f2-a3b4-5678-2345-901234567890"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Modern web technologies and full-stack development",
                            IsActive = true,
                            ProgramName = "Web Development"
                        },
                        new
                        {
                            EnrollmentId = new Guid("5e6f7080-90a0-2345-ef01-345678901235"),
                            CampusId = new Guid("b4c5d6e7-f8a9-0123-7890-456789012345"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Oral health care and preventive dental services",
                            IsActive = true,
                            ProgramName = "Dental Hygiene"
                        },
                        new
                        {
                            EnrollmentId = new Guid("6f708090-a0b0-3456-f012-456789012346"),
                            CampusId = new Guid("f2a3b4c5-d6e7-8901-5678-234567890123"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Animal care and veterinary assistant training",
                            IsActive = true,
                            ProgramName = "Veterinary Technology"
                        },
                        new
                        {
                            EnrollmentId = new Guid("708090a0-b0c0-4567-0123-567890123457"),
                            CampusId = new Guid("a7b8c9d0-e1f2-3456-0123-789012345678"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Certificate",
                            Description = "Advanced welding techniques and metallurgy",
                            IsActive = true,
                            ProgramName = "Welding Technology"
                        },
                        new
                        {
                            EnrollmentId = new Guid("8090a0b0-c0d0-5678-1234-678901234568"),
                            CampusId = new Guid("d0e1f2a3-b4c5-6789-3456-012345678901"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Arts",
                            Description = "Visual communication and digital design",
                            IsActive = true,
                            ProgramName = "Graphic Design"
                        },
                        new
                        {
                            EnrollmentId = new Guid("90a0b0c0-d0e0-6789-2345-789012345679"),
                            CampusId = new Guid("d0e1f2a3-b4c5-6789-3456-012345678901"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Bachelor of Science",
                            Description = "Law enforcement and criminal investigation",
                            IsActive = true,
                            ProgramName = "Criminal Justice"
                        },
                        new
                        {
                            EnrollmentId = new Guid("a0b0c0d0-e0f0-789a-3456-890123456780"),
                            CampusId = new Guid("c5d6e7f8-a9b0-1234-8901-567890123456"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Arts",
                            Description = "Child development and early learning education",
                            IsActive = true,
                            ProgramName = "Early Childhood Education"
                        },
                        new
                        {
                            EnrollmentId = new Guid("b0c0d0e0-f0a1-89ab-4567-901234567891"),
                            CampusId = new Guid("a7b8c9d0-e1f2-3456-0123-789012345678"),
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Degree = "Associate of Applied Science",
                            Description = "Heating, ventilation, and air conditioning systems",
                            IsActive = true,
                            ProgramName = "HVAC Technology"
                        });
                });

            modelBuilder.Entity("LearnerCenter.API.Models.Term", b =>
                {
                    b.Property<Guid>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegistrationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TermCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TermId");

                    b.HasIndex("TermCode")
                        .IsUnique();

                    b.ToTable("Terms");

                    b.HasData(
                        new
                        {
                            TermId = new Guid("11111111-aaaa-bbbb-cccc-111111111111"),
                            CreatedDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RegistrationEndDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationStartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TermCode = "F24",
                            TermName = "Fall 2024"
                        },
                        new
                        {
                            TermId = new Guid("22222222-bbbb-cccc-dddd-222222222222"),
                            CreatedDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RegistrationEndDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationStartDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TermCode = "S25",
                            TermName = "Spring 2025"
                        },
                        new
                        {
                            TermId = new Guid("33333333-cccc-dddd-eeee-333333333333"),
                            CreatedDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RegistrationEndDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationStartDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TermCode = "SU25",
                            TermName = "Summer 2025"
                        },
                        new
                        {
                            TermId = new Guid("44444444-dddd-eeee-ffff-444444444444"),
                            CreatedDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RegistrationEndDate = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationStartDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TermCode = "F25",
                            TermName = "Fall 2025"
                        });
                });

            modelBuilder.Entity("LearnerCenter.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LearnerCenter.API.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("LearnerCenter.API.Models.Course", b =>
                {
                    b.HasOne("LearnerCenter.API.Models.Enrollment", "Enrollment")
                        .WithMany("Courses")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("LearnerCenter.API.Models.Enrollment", b =>
                {
                    b.HasOne("LearnerCenter.API.Models.Campus", "Campus")
                        .WithMany("Enrollments")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("LearnerCenter.API.Models.User", b =>
                {
                    b.HasOne("LearnerCenter.API.Models.Enrollment", "CurrentEnrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentEnrollment");
                });

            modelBuilder.Entity("LearnerCenter.API.Models.UserProfile", b =>
                {
                    b.HasOne("LearnerCenter.API.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("LearnerCenter.API.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnerCenter.API.Models.Campus", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("LearnerCenter.API.Models.Enrollment", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LearnerCenter.API.Models.User", b =>
                {
                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
